# To install httpd and setup with a index.html file

- hosts:
  - all
  tasks:
  - name: "Install Apache"
    yum: 
      name: httpd
      state: latest
    become: true

  - name: Start service httpd, if not running
    service:
      name: httpd
      state: started
    become: true

  - name: Create index.html file
    copy: 
      dest: "/var/www/html/index.html"
      content: "<h1>Hello World!!</h1>"
    become: true

  - name: Reload service httpd, in all cases
    service:
      name: httpd
      state: reloaded
    become: true
